### ISSUE TITLE
Cam error- failed to get frame on time

### ISSUE THREAD

**Issue by ziza150** [lemariva/uPyCam#9]
Hi!

I have a problem with ESP32-CAM. I have tried webcam but when open webpage with relevant IP address I see long loading page. At this point serial connection repeats:

E (102605) camera: Failed to get the frame on time!
E (102605) camera: Camera Capture Failed
bh 0x00372a9f
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff
bh 0x00ffdaff

and after a while page stops loading and serial terminal writes:

ERROR:picoweb:<Stream object at 3f94cbb0>: EOF on request start
INFO:picoweb:648500299.454 <HTTPRequest object at 3f950de0> <Stream object at 3f950c10> "GET /favicon.ico"

I did flashed ESP32 chip with binary file (micropython_3a9d948_esp32_idf4.x_ble_camera.bin). I cloned uPyCam repository and uploaded it on the board via uPyCraft (V1.1)(Could it be problem that I haven't use VSCode?). Then I have installed picoweb (1.8.2), micropython-ulogging (0.3) and usjon (Error, packages may be partially installed) and replaced file __init__.py and core.py in uasyncio folder. Finally files on the board look like this.

![Files](https://user-images.githubusercontent.com/68515317/87883101-3faa6400-ca05-11ea-83b5-ba3ded8f2eb4.png)

I couldn't find any solution for my issue.
Thanks for any ideas!

**Comment by lemariva** [comment]
uPyCraft should not be the problem. Did you change the pins in the config.py file to match your setup? I think that is the problem.

**Comment by lemariva** [comment]
any news?

**Comment by ziza150** [comment]
Hi, 
sorry for late reply. Turned out that the problem was camera itself. I tried camera without micropython, through Arduino IDE and other formats (YUV422, Grayscale) worked on specific settings (VGA resolution, xclk 10Mhz) only except JPEG.

So I bought better camera and now all format works as well as with your setup.

Thanks.
